server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # Server itself, must not register with itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # No min number of registered instances
    wait-time-in-ms-when-sync-empty: 0
    # Reduce eviction interval to remove crashed instances fast
    eviction-interval-timer-in-ms: 5000
